### PR TITLE
WIP: New package format

### LINKED ISSUE #3: Failed to compile
```
ERROR in ./node_modules/angular-wormhole/index.ts
Module build failed: Error: C:\dev\angular\ng-hn\node_modules\angular-wormhole\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\dev\angular\ng-hn\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (C:\dev\angular\ng-hn\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### PR DESCRIPTION
**Pull request by medokin**
I have created a angular-cli 6 library around the Component to fix #3
This includes packaging, tests and so on.

**TODO:** 
- Rename library to angular-wormhole (ng-wormhole now)
- Include stuff from current version (readme, license, changelog, etc.)

Recommended version change: **Major**

It is kind of **urgent**. Are you interested in this changes and should I proceed?
If not, I can release my fork as _ng-wormhole_.

### CODE REVIEW

**Comment by topaxi** [comment]
I don't have much time to work on this myself, but I'd be happy to accept the pull request and release a new major version once you are finished. :+1:

**Comment by topaxi** [comment]
As `ng-wormhole` is still available on npmjs, lets leave it as `ng-wormhole` for the next version and deprecate the old `angular-wormhole` package.

**Comment by topaxi** [comment]
I'm not yet sure how to properly publish this to npm with the new setup, if you could point me in the right direction I will publish this thing as version 2.0.0.

**Comment by medokin** [comment]
https://github.com/topaxi/angular-wormhole/blob/master/package.json#L13
`npm run package` does the job 👍 

The ready to publish tgz can be found in dist/ng-wormhole

Ping me if you need more assistance. Happy to help.

**Comment by topaxi** [comment]
Sorry for all the noise, I figured it out and published your changes under `angular-wormhole@2.0.0` and `ng-wormhole@2.0.0`. I've also deprecated `angular-wormhole` on npm.

**Comment by topaxi** [comment]
Thanks a lot! <3

**Comment by medokin** [comment]
Nothing to be sorry about. Just tested the new Release, it works well.
Thank you!

**Pull request merged**
